export const metadata = {
  title: "page | installation page",
  description: "Generated by create next app",
};

const Installation = () => {
    return (
        <div>
            <h1>Installation</h1>
        </div>
    );
};

export default Installation;